#!/usr/bin/env bash
RED='\033[0;31m'
NC='\033[0m' # No Color
GREEN='\033[0;32m'
APPEND=
args=("$@")
set -e

longopt(){
while [[ $# -gt 0 ]]; do
  key="$1"
  case "${key}" in
   *source*|s) REPO="$2" ;;
   *append*|a) APPEND=-a ;;
   *pattern*|p) PATTERN="$2" ;; 
   *help*|h) help ;;
  :) break ;;
  esac
  shift
done
printf "I ${RED}love ${GREEN}Stack Overflow ${NC}\n"
}


help() {
  cat <<EOF
Help:
     this bash script copy .gitignore file from  available web source to current path,
     the default source of choice is github/gitignore youc can privde your source url with source (-s) flag. 
     If you want to append to existing .gitignore content specy -a append flag. skip -a if want to recreate .gitignore file
     call it right way  with argument < name of .gitignore as node, python, etc > or -h option to show this message 

list of options:
     -a (--append)  Append to .gitignore
     -p (--pattern) Pattern to search for
     -s (--source)  repo/reponame as source where to search .gitignore pattern
     -h (--help)    show this help

Dependencies have to be installed before use: jq  (https://stedolan.github.io/jq)
Comments to: @tst32
EOF
exit 0
}



usage() {
  cat <<EOF
usage:
     if you want fastly create a .gitignore in current project folder from a usefull guthub templates
     then try gh-gitignore command-line tool. With this you can combine by append as many templates 
     as you want, and use custom source to search templates for, see more by 
     gh gitignore --help
EOF
}

if [ $# -eq 0 ]; then
  usage
  exit 1
fi

command -v gh >/dev/null 2>&1 || {
  echo >&2 "require gh (https://cli.github.com/) tool, but it's not installed.  Aborting."
  exit 1
}
command -v jq >/dev/null 2>&1 || {
  echo >&2 "require jq (https://stedolan.github.io/jq/) tool, but it's not installed.  Aborting."
  exit 1
}

while getopts s:p:ha-: flag; do
  case "${flag}" in
  s) REPO=${OPTARG} ;;
  p) PATTERN=${OPTARG} ;;
  h) help ;;
  a) APPEND=-a ;;
  -) longopt ${OPTARG};;
  :) longopt "$@" ;;
  esac
done




if [[ -z "$REPO" ]]; then
  REPO="github/gitignore"
  longopt "$@"
  printf " in default source github/gitignore, will search for ${PATTERN}  "
fi

CONTENT=$(gh api repos/${REPO}/contents --jq .[].name | grep ".gitignore" | tr '\n' ', ')
NAME=$(gh api repos/${REPO}/contents --jq .[].name | grep ".gitignore" | grep -i "$PATTERN")

printf "try to found $PATTERN"
echo -e ""

if [[ ${NAME} = "" ]]; then
  echo -e " error: no file selected.\n\n Please select .gitignore file to download. look at possible options: "
  printf "$CONTENT \b\b\b"
  echo -e ""
  exit 1
fi

curl -s https://raw.githubusercontent.com/${REPO}/master/${NAME} | tee ${APPEND} .gitignore
echo -e ""
echo -e "${GREEN}\n✓${NC} Downloaded ${PATTERN} to ${PWD}/.gitignore"